---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ntdt/unzip

inputs:
- name: cachet-cf
- name: cachet-release

outputs:
- name: app-manifest-output
- name: cachet-cf-app

run:
  path: cachet-cf/ci/tasks/prepare-app-manifest.sh
