resources:
- name: cachet-cf
  type: git
  source:
    uri: https://github.com/ntdt/Cachet-cf.git
    branch: master
- name: tool-om
  type: github-release
  source:
    owner: pivotal-cf
    repository: om

jobs:
- name: get-deployed-products
  plan:
  - aggregate:
    - get: cachet-cf
      trigger: false
    - get: tool-om
      params:
        globs:
        - "om-linux"
  - task: get-deployed-products
    file: tasks/get-deployed-products.yml
    params:
      pcf_ert_domain: {{pcf_ert_domain}}
      pcf_opsman_admin: {{pcf_opsman_admin}}
      pcf_opsman_admin_passwd: {{pcf_opsman_admin_passwd}}
      
